**Name: Kshitij Amitkumar Mondal<br>
Roll No: TCOD-73<br>
Class: TE-D<br>
Batch: T12**

# Assignment No: 5
Title of the Assignment:
1. Implement logistic regression using Python/R to perform classification on
Social_Network_Ads.csv dataset.
2. Compute Confusion matrix to find TP, FP, TN, FN, Accuracy, Error rate, Precision,
Recall on the given dataset.

Import libraries and create alias for Pandas, Numpy and Matplotlib

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("/content/Social_Network_Ads.csv")

In [ ]:
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [ ]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [ ]:
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
data = pd.get_dummies(df, drop_first=True)

In [ ]:
x = data.drop(['Purchased'], axis = 1)
y = data['Purchased']

In [ ]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size =0.2,random_state = 0)

In [ ]:
xtrain

      User ID  Age  EstimatedSalary  Gender_Male
336  15664907   58           144000         True
64   15605000   59            83000        False
55   15649136   24            55000        False
106  15706185   26            35000        False
300  15736397   58            38000        False
..        ...  ...              ...          ...
323  15619465   48            30000        False
192  15779581   29            43000         True
117  15591433   36            52000         True
47   15776348   27            54000        False
172  15794661   26           118000        False

[320 rows x 4 columns]

In [ ]:
xtest

      User ID  Age  EstimatedSalary  Gender_Male
132  15725660   30            87000         True
309  15652400   38            50000        False
341  15776844   35            75000         True
196  15738448   30            79000        False
246  15638003   35            50000        False
..        ...  ...              ...          ...
14   15628972   18            82000         True
363  15768293   42            79000        False
304  15598070   40            60000        False
361  15778830   53            34000        False
329  15639576   47           107000        False

[80 rows x 4 columns]

In [ ]:
ytrain

336    1
64     0
55     0
106    0
300    1
      ..
323    1
192    0
117    0
47     0
172    0
Name: Purchased, Length: 320, dtype: int64

In [ ]:
ytest

132    0
309    0
341    0
196    0
246    0
      ..
14     0
363    0
304    0
361    1
329    1
Name: Purchased, Length: 80, dtype: int64

Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
model = logreg.fit(xtrain,ytrain)

In [ ]:
ytrain_pred = logreg.predict(xtrain)
ytest_pred = logreg.predict(xtest)

In [ ]:
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, confusion_matrix, classification_report
)

Accuracy Score

In [ ]:
print(accuracy_score(ytrain, ytrain_pred))

0.825

In [ ]:
print(accuracy_score(ytest, ytest_pred))

0.9125

Error Rate

In [ ]:
print(1-accuracy_score(ytrain, ytrain_pred))

0.17500000000000004

In [ ]:
print(1-accuracy_score(ytest, ytest_pred))

0.08750000000000002

Precision Score

In [ ]:
precision_score(ytrain, ytrain_pred)

0.8217821782178217

In [ ]:
precision_score(ytest, ytest_pred)

0.8947368421052632

Recall Score

In [ ]:
recall_score(ytrain, ytrain_pred)

0.6859504132231405

In [ ]:
recall_score(ytest, ytest_pred)

0.7727272727272727

Classification Report

In [ ]:
print(classification_report(ytrain, ytrain_pred))

              precision    recall  f1-score   support

           0       0.83      0.91      0.87       199
           1       0.82      0.69      0.75       121

    accuracy                           0.82       320
   macro avg       0.82      0.80      0.81       320
weighted avg       0.82      0.82      0.82       320

In [ ]:
print(classification_report(ytest, ytest_pred))

              precision    recall  f1-score   support

           0       0.92      0.97      0.94        58
           1       0.89      0.77      0.83        22

    accuracy                           0.91        80
   macro avg       0.91      0.87      0.89        80
weighted avg       0.91      0.91      0.91        80

Confusion Matrix

In [ ]:
print(confusion_matrix(ytrain, ytrain_pred))

[[181  18]
 [ 38  83]]

In [ ]:
print(confusion_matrix(ytest, ytest_pred))

[[56  2]
 [ 5 17]]

F1 Score

In [ ]:
f1_score(ytrain, ytrain_pred)

0.7477477477477478

In [ ]:
f1_score(ytest, ytest_pred)

0.8292682926829268

Execution with Formulas

Accuracy

In [ ]:
accuracy_train = np.sum(ytrain == ytrain_pred) / len(ytrain)
print(accuracy_train)

0.825

In [ ]:
accuracy_test = np.sum(ytest == ytest_pred) / len(ytest)
print(accuracy_test)

0.9125

Error Rate

In [ ]:
error_train = 1 - (np.sum(ytrain == ytrain_pred) / len(ytrain))
print(error_train)

0.17500000000000004

In [ ]:
error_test = 1 - (np.sum(ytest == ytest_pred) / len(ytest))
print(error_test)

0.08750000000000002

Precision

In [ ]:
tp = np.sum((ytrain == 1) & (ytrain_pred == 1))
fp = np.sum((ytrain == 0) & (ytrain_pred == 1))
precision_train = tp / (tp + fp)
print(precision_train)

0.8217821782178217

In [ ]:
tp = np.sum((ytest == 1) & (ytest_pred == 1))
fp = np.sum((ytest == 0) & (ytest_pred == 1))
precision_test = tp / (tp + fp)
print(precision_test)

0.8947368421052632

Recall

In [ ]:
tp = np.sum((ytrain == 1) & (ytrain_pred == 1))
fn = np.sum((ytrain == 1) & (ytrain_pred == 0))
recall_train = tp / (tp + fn)
print(recall_train)

0.6859504132231405

In [ ]:
tp = np.sum((ytest == 1) & (ytest_pred == 1))
fn = np.sum((ytest == 1) & (ytest_pred == 0))
recall_test = tp / (tp + fn)
print(recall_test)

0.7727272727272727

F1 Score

In [ ]:
tp = np.sum((ytrain == 1) & (ytrain_pred == 1))
fp = np.sum((ytrain == 0) & (ytrain_pred == 1))
fn = np.sum((ytrain == 1) & (ytrain_pred == 0))
f1_train = (2 * tp) / (2 * tp + fp + fn)
print(f1_train)

0.7477477477477478

In [ ]:
tp = np.sum((ytest == 1) & (ytest_pred == 1))
fp = np.sum((ytest == 0) & (ytest_pred == 1))
fn = np.sum((ytest == 1) & (ytest_pred == 0))
f1_test = (2 * tp) / (2 * tp + fp + fn)
print(f1_test)

0.8292682926829268